### ISSUE TITLE
Wayland support status tracking

### ISSUE THREAD

**Issue by kyu-n** [flathub/com.pokemmo.PokeMMO#28]
This issue tracks problems blocking switching to Wayland-by-default.

- [ ] Currently, players can break their game config by switching to an unsupported compositor -- _This issue is fixed pending release upstream_
- [ ] The game client forces X11 by default when initializing config options
- [ ] The game client utilizes Swing for Java when spawning the internal Updater
- [ ] The unix wrapper project utilizes Swing for Java when starting. This fails to start on Wayland entirely

Swing does not support Wayland and will not for the foreseeable future. On platforms which are managed by external wrappers [snapcraft, flathub, macos], we should defer updating to said wrapper

[Swingland](https://git.sr.ht/~phlash/swingland) is disgustingly jank, but may be useful here since the core application is so simple. Longterm, Eclipse SWT is probably the better choice though

A point of concern is how best to determine whether the game client is running in an X11 or Wayland environment. Upstream, we currently assume that if `XDG_SESSION_TYPE` is set to `wayland` or a `WAYLAND_DISPLAY` var is set, we support Wayland. Whether this is resilient enough for bad distros is yet to be seen

**Comment by rabidrivas** [comment]
Not really a dev, so I don't know so I don't know if this is the the correct place to post this. But tried the flatpak for the new Update and got a PFNA error. Enabling wayland support on the kde settings seemed to fix it. 

I am running Nobara 40 (Fedora based), on wayland.

This permissions should probably be on by default

**Comment by kyu-n** [comment]
All outstanding flatpak-specific issues have been resolved. This issue will be resolved when the next upstream game client release is done.
